# @Author: Ethen Kuether <ekuther>
# @Email:  ekuether@unomaha.edu
# @Filename: docker-compose.yml
# @Last modified by:   Ethen Kuether

version: "1"
services:
  node:
    build: .
    restart: always
    volumes:
      - ./backend:/var/www/backend
    expose:
     - "3000"
    depends_on:
     - db
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
