# @Author: Matthew Hale <matthale>
# @Date:   2017-09-05T12:29:08-05:00
# @Email:  mlhale@unomaha.edu
# @Filename: docker-compose.yml
# @Last modified by:   matthale
# @Last modified time: 2018-09-06T15:21:50-05:00
# @Copyright: Copyright (C) 2018 Matthew L. Hale



version: "2"
services:
  node:
    build: .
    restart: always
    volumes:
      - ./backend:/var/www/backend
    expose:
     - "3000"
    depends_on:
     - db
  db:
    restart: always
    image: postgres
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
