# @Author: Ethen Kuether <ekuther>
# @Email:  ekuether@unomaha.edu
# @Filename: docker-compose.yml
# @Last modified by:   Ethen Kuether

version: "1"
services:
  node:
    build: .
    restart: always
    ports:
     - "3000:3000"
    links:
     - db
  db:
    build: ./backend/Database/.
    restart: always
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
